project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "../"
preserve_hierarchy: true

files:
  - source: ".github/translations/unraid-webgui.po"
    translation: "emhttp/languages/%locale%/unraid-webgui.po"
  - source: ".github/translations/unraid-webgui-js.po"
    translation: "emhttp/languages/%locale%/unraid-webgui-js.po"
  - source: "emhttp/languages/en_US/helptext.txt"
    translation: "emhttp/languages/%locale%/helptext.txt"