#!/bin/bash
# btrfs_check start <dev> <id> <options>
# btrfs_check status <dev> <id>
# btrfs_check cancel <dev> <id>
# btrfs_check reset <mountpoint>

FSCK="/sbin/btrfs check"

[[ $1 == reset ]] && exec /sbin/btrfs device stats -z "$2"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/check.source"
