#!/bin/bash
# exfat_check start <dev> <id> <options>
# exfat_check status <dev> <id>
# exfat_check cancel <dev> <id>

FSCK="/sbin/fsck.exfat"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/check.source"
