#!/bin/bash
# ext_check start <dev> <id> <options>
# ext_check status <dev> <id>
# ext_check cancel <dev> <id>

FSCK="/sbin/e2fsck"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/check.source"
