#!/bin/bash
# ntfs_check start <dev> <id> <options>
# ntfs_check status <dev> <id>
# ntfs_check cancel <dev> <id>

FSCK="/bin/ntfsfix"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/check.source"
