#!/bin/bash
# reiserfs_check start <dev> <id> <options>
# reiserfs_check status <dev> <id>
# reiserfs_check cancel <dev> 

FSCK="/sbin/reiserfsck --yes --quiet"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/check.source"
