#!/bin/bash
SERVICES="sshd avahidaemon samba rpc nfsd ntpd nginx"

[[ -n $1 && -e /tmp/atjob.tmp ]] && exit 0
for cmd in $SERVICES; do
  if /etc/rc.d/rc.$cmd update; then
    /etc/rc.d/rc.$cmd reload >/dev/null 2>&1
  fi
done
touch /tmp/atjob.tmp
exit 0
