#!/bin/bash
SERVICES="rpc nfsd ntpd nginx sshd avahidaemon samba"

if [[ -n $1 ]]; then
  [[ ! -e $1 ]] && touch $1 || exit 0
fi

for cmd in $SERVICES; do
  /etc/rc.d/rc.$cmd update >/dev/null 2>&1
done
exit 0
