#!/bin/bash
SERVICES="sshd avahidaemon samba rpc nfsd ntpd nginx"

if [[ -n $1 ]]; then
  [[ ! -e $1 ]] && touch $1 || exit 0
fi
for cmd in $SERVICES; do
  if /etc/rc.d/rc.$cmd update; then
    /etc/rc.d/rc.$cmd reload >/dev/null 2>&1
  fi
done
exit 0
