#!/bin/bash

CALLER="show"

# library functions
. /etc/rc.d/rc.library.source

# include IP addresses?
if check && [[ $1 == ip ]]; then
  IP=()
  for NET in $BIND; do
    IP+=("$NET [$(echo $(show dev $NET)|xargs)]")
  done
  BIND=${IP[@]}
fi

# return list
echo $BIND
