#!/bin/bash
NGINX="/usr/sbin/nginx"
CONF="/etc/nginx/nginx.conf"
LOG="/var/log/nginx/error.log"

while :; do
  # check log for nginx socket errors
  if tail -3 $LOG 2>/dev/null|grep -q 'open socket'; then
    # hard restart
    logger -t monitor "Restarting nginx"
    pkill -f $NGINX
    sleep 1
    # remove open socket errors from LOG
    sed -ri '/alert.+?(open socket|aborting)/d' $LOG
    $NGINX -c $CONF 2>/dev/null
  fi
  # check every 10 seconds
  sleep 10
done &
disown %%
