#!/usr/bin/php
<?PHP
// todo: this should generate/publish json-encoded string and let subscriber handle html
require_once "/usr/local/emhttp/webGui/include/publish.php";
$var = @parse_ini_file("/var/local/emhttp/var.ini");
$fsState=$var['fsState'];
if ($fsState == "Stopped")
    $state = "<span class='red strong'>Array Stopped</span>";
elseif ($fsState == "Starting")
    $state = "<span class='orange strong'>Array Starting</span>";
else {
    $state = "<span class='green strong'>Array Started</span>";
    $mdResync = $var['mdResync'];
    if ($mdResync > 0) {
        $mdResyncAction = $var['mdResyncAction'];
        if (strstr($mdResyncAction, "recon"))     $action="Parity-Sync / Data-Rebuild";
        elseif (strstr($mdResyncAction, "clear")) $action="Clearing";
        elseif ($mdResyncAction == "check")       $action="Read-Check";
        elseif (strstr($mdResyncAction, "check")) $action="Parity-Check";
        $mdResyncPos = $var['mdResyncPos'];
        $progress = number_format($mdResyncPos/($mdResync/100+1),1);
        $state .= "&bullet;<span class='orange strong'>$action $progress %</span>";
    }
}
publish("watchdog", $state);
?>
