#!/bin/bash
ini=/var/local/emhttp/diskload.ini
declare -a sector reads writes

# t = poll interval in seconds
t=6
# get sector size of each disk
c=0
for dev in $(awk '/(sd[a-z]*|nvme[0-9]n1) /{print $3}' /proc/diskstats); do
  sector[c]=$(cat /sys/block/$dev/queue/hw_sector_size 2>/dev/null)
  [[ -z ${sector[c]} ]] && sector[c]=512
  ((c++))
done

# start daemon
while :; do
  stats=($(awk '/(sd[a-z]*|nvme[0-9]n1) /{print $3,$6,$10}' /proc/diskstats))
  c=0; s=${#stats[@]}
  echo -n >$ini
  for ((i=0;i<s;i+=3)); do
    reads[c]=$((stats[i+1]-reads[c]))
    writes[c]=$((stats[i+2]-writes[c]))
    echo ${stats[i]}=$((reads[c]*sector[c]/t)) $((writes[c]*sector[c]/t)) >>$ini
    reads[c]=${stats[i+1]}
    writes[c]=${stats[i+2]}
    ((c++))
  done
  sleep $t
done &
