#!/usr/bin/php -q
<?PHP
/* Copyright 2005-2021, Lime Technology
 * Copyright 2012-2021, Bergware International.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 2,
 * as published by the Free Software Foundation.
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 */
?>
<?
$stamps = '/var/tmp/stamps.ini';
$mdcmd  = '/usr/local/sbin/mdcmd';

function mdstat($key) {
  return exec("grep -Po '^$key=\K\d+' /proc/mdstat");
}

if (mdstat('mdResyncPos')>0) {
  switch ($argv[1]) {
  case 'pause':
    if (mdstat('sbSynced')>0) {
      if (!file_exists($stamps)) file_put_contents($stamps,parse_ini_file('/var/local/emhttp/var.ini')['sbSynced']);
      file_put_contents($stamps,','.time(),FILE_APPEND);
      exec("$mdcmd nocheck pause");
    }
    break;
  case 'resume':
    if (mdstat('sbSynced')==0) {
      file_put_contents($stamps,','.time(),FILE_APPEND);
      exec("$mdcmd check resume");
    }
    break;
  }
}
?>
