#!/bin/bash
SERVICES="sshd nginx avahidaemon samba rpc nfsd ntpd"

for cmd in $SERVICES; do
  [[ $cmd == $1 ]] && option=renew || option=reload
  if /etc/rc.d/rc.$cmd update; then
    /etc/rc.d/rc.$cmd $option >/dev/null 2>&1
  fi
done
