#!/usr/bin/php -q
<?PHP
/* Copyright 2005-2021, Lime Technology
 * Copyright 2012-2021, Bergware International.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 2,
 * as published by the Free Software Foundation.
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 */
?>
<?
$docroot = '/usr/local/emhttp';
$notify  = "$docroot/webGui/scripts/notify";
$unread  = '';

require_once "$docroot/webGui/include/publish.php";

while (true) {
  $get = shell_exec("$notify get");
  if ($get != $unread) {
    publish('notify', $get);
    $unread = $get;
  }
  sleep(3);
}
?>
