#!/usr/bin/php -q
<?PHP
/* Copyright 2005-2022, Lime Technology
 * Copyright 2012-2022, Bergware International.
 * Copyright 2015, Dan Landon.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 2,
 * as published by the Free Software Foundation.
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 */
?>
<?
$docroot  = '/usr/local/emhttp';

require_once "$docroot/webGui/include/Wrappers.php";
require_once "$docroot/webGui/include/publish.php";
extract(parse_plugin_cfg('dynamix',true));

// add translations
$_SERVER['REQUEST_URI'] = 'settings';
$login_locale = $display['locale'];
require_once "$docroot/webGui/include/Translations.php";

// remember current language
$locale_init = $locale;

$state = [
  'TRIM ONLINE'  => _('Online (trim)'),
  'BOOST ONLINE' => _('Online (boost)'),
  'ONLINE'       => _('Online'),
  'SLAVE'        => _('Slave'),
  'ONBATT'       => _('On battery'),
  'COMMLOST'     => _('Lost communication'),
  'NOBATT'       => _('No battery detected')
];

$red    = "class='red-text'";
$green  = "class='green-text'";
$orange = "class='orange-text'";

function update_translation($locale) {
  global $docroot,$language;
  $language = [];
  if ($locale) {
    $text = "$docroot/languages/$locale/translations.txt";
    if (file_exists($text)) {
      $store = "$docroot/languages/$locale/translations.dot";
      if (!file_exists($store)) file_put_contents($store,serialize(parse_lang_file($text)));
      $language = unserialize(file_get_contents($store));
    }
    $text = "$docroot/languages/$locale/settings.txt";
    if (file_exists($text)) {
      $store = "$docroot/languages/$locale/settings.dot";
      if (!file_exists($store)) file_put_contents($store,serialize(parse_lang_file($text)));
      $language = array_merge($language,unserialize(file_get_contents($store)));
    }
  }
}
while (true) {
  // check for language changes
  extract(parse_plugin_cfg('dynamix',true));
  if ($display['locale'] != $locale_init) {
    $locale_init = $display['locale'];
    update_translation($locale_init);
  }
  unset($status,$rows,$power,$load,$freq,$output);
  $status = array_fill(0,6,"<span>-</span>");
  if (file_exists("/var/run/apcupsd.pid")) {
    // get battery-level and runtime settings
    $cfg = parse_plugin_cfg('dynamix.apcupsd');
    $level = $cfg['BATTERYLEVEL'] ?: 10;
    $runtime = $cfg['MINUTES'] ?: 5;
    exec("/sbin/apcaccess 2>/dev/null", $rows);
    foreach ($rows as $row) {
      [$key, $val] = array_map('trim', explode(':', $row, 2));
      switch ($key) {
      case 'STATUS':
        $val = strtr($val, $state);
        $status[0] = $val ? (stripos($val,'online')!==false ? "<span $green>$val</span>" : "<span $red>$val</span>") : "<span $orange>"._('Refreshing')."...</span>";
        break;
      case 'BCHARGE':
        [$val,$unit] = explode(' ', $val, 2);
        $val = intval($val);
        $status[1] = strtok($val,' ')>$level ? "<span $green>$val $unit</span>" : "<span $red>$val $unit</span>";
        break;
      case 'TIMELEFT':
        [$val,$unit] = explode(' ', $val, 2);
        $val = intval($val);
        $status[2] = $val>$runtime ? "<span $green>$val $unit</span>" : "<span $red>$val $unit</span>";
        break;
      case 'NOMPOWER':
        $power = strtok($val,' ');
        $status[3] = $power==0 ? "<span $red>$val</span>" : "<span $green>$val</span>";
        break;
      case 'LOADPCT':
        $load = strtok($val,' ');
        $status[4] = $val;
        break;
      case 'OUTPUTV':
        $output = strtok($val,' ');
        $status[5] = $val;
        break;
      case 'NOMINV':
        $volt = strtok($val,' ');
        $minv = $volt / 1.1; // +/- 10% tolerance
        $maxv = $volt * 1.1;
        break;
      case 'LINEFREQ':
        $freq = $val;
        break;
      }
    }
    if ($power && isset($load)) $status[4] = ($load<90 ? "<span>" : "<span $red>").intval($power*$load/100)." W (".$status[4].")</span>";
    elseif (isset($load)) $status[4] = ($load<90 ? "<span>" : "<span $red>").$status[4]."</span>";
    $status[5] = $output ? (($output<$minv||$output>$maxv ? "<span $red>" : "<span $green>").$status[5].($freq ? " / $freq" : "")."</span>") : $status[5];
  }
  publish('apcups',implode(';', $status));
  sleep(3);
}
?>
