#!/usr/bin/php -q
<?PHP
/* Copyright 2005-2023, Lime Technology
 * Copyright 2012-2023, Bergware International.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 2,
 * as published by the Free Software Foundation.
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 */
?>
<?
$docroot = '/usr/local/emhttp';
$notify  = "$docroot/webGui/scripts/notify";

require_once "$docroot/webGui/include/publish.php";

while (true) {
  publish('notify', shell_exec("$notify get"));
  sleep(3);
}
?>
