#!/usr/bin/php -q
<?PHP
/* Copyright 2005-2023, Lime Technology
 * Copyright 2012-2023, Bergware International.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 2,
 * as published by the Free Software Foundation.
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 */
?>
<?
$docroot = '/usr/local/emhttp';
$varroot = '/var/local/emhttp';

require_once "$docroot/webGui/include/publish.php";
require_once "$docroot/webGui/include/Wrappers.php";

$csrf_old = '';
while (true) {
  $csrf_new = @parse_ini_file("$varroot/var.ini")['csrf_token'];
  if ($csrf_new !== $csrf_old) {
    publish('session', $csrf_new);
    $csrf_old = $csrf_new;
  }
  sleep(10);
}
?>
