#!/usr/bin/php -q
<?PHP
/* Copyright 2005-2025, Lime Technology
 * Copyright 2012-2025, Bergware International.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 2,
 * as published by the Free Software Foundation.
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 */
?>
<?
$docroot = '/usr/local/emhttp';
require_once "$docroot/webGui/include/publish.php";
require_once "$docroot/webGui/include/Wrappers.php";

while (true) {
  if (file_exists('/var/local/emhttp/wireless.ini')) {
    $up = file_get_contents('/sys/class/net/wlan0/carrier')==1;
    $color = $up ? 'blue-text' : 'red-text';
  } else {
    $color = 'grey-text';
  }
  publish('wlan0',$color);
  sleep(5);
}
?>
