#!/usr/bin/php -q
<?PHP
/* Copyright 2005-2023, Lime Technology
 * Copyright 2012-2023, Bergware International.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 2,
 * as published by the Free Software Foundation.
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 */
?>
<?
$docroot ??= ($_SERVER['DOCUMENT_ROOT'] ?: '/usr/local/emhttp');
require_once "$docroot/webGui/include/Wrappers.php";
extract(parse_plugin_cfg('dynamix',true));

// add translations
$_SERVER['REQUEST_URI'] = 'plugins';
$login_locale = _var($display,'locale');
require_once "$docroot/webGui/include/Translations.php";
require_once "$docroot/webGui/include/publish.php";

$nchan = $argv[$argc-1] == 'nchan'; // console or nchan output

function write(...$messages){
  global $nchan;
  if ($nchan) {
    foreach ($messages as $message) {
      publish('plugins', $message);
    }
  } else {
    foreach ($messages as $message) echo $message;
  }
}

write(_("Checking connectivity")." ...\n");
if (check_network_connectivity()) {
  $check = popen('plugin checkall','r');
  while (!feof($check)) write(fgets($check));
  pclose($check);
} else {
  write(_("No response, aborting")."!\n");
}
if ($nchan) write('_DONE_','');
?>