#!/usr/bin/php -q
<?PHP
/* Copyright 2005-2023, Lime Technology
 * Copyright 2012-2023, Bergware International.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 2,
 * as published by the Free Software Foundation.
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 */
?>
<?
$docroot ??= ($_SERVER['DOCUMENT_ROOT'] ?: '/usr/local/emhttp');
require_once "$docroot/webGui/include/Wrappers.php";
require_once "$docroot/plugins/dynamix.plugin.manager/include/PluginHelpers.php";

// Multi-language support
if (!function_exists('_')) {
  function _($text) {return $text;}
}

extract(parse_plugin_cfg('dynamix', true));

$var     = (array)@parse_ini_file('/var/local/emhttp/var.ini');
$script  = "$docroot/webGui/scripts/notify";
$server  = strtoupper(_var($var,'NAME','server'));
$output  = _var($notify,'plugin');
$builtin = ['unRAIDServer'];

foreach ($builtin as $name) {
  $plg  = "$name.plg";
  plugin('check',$plg);
  $file = "/tmp/plugins/$plg";
  $old  = plugin('version', "/var/log/plugins/$plg");
  $new  = plugin('version', $file);

  // silently suppress bad download of PLG file
  if (version_compare($new,$old,'>')) {
    exec("$script -e ".escapeshellarg("System - $name [$new]")." -s ".escapeshellarg("Notice [$server] - Version update $new")." -d ".escapeshellarg("A new version of $name is available")." -i ".escapeshellarg("normal $output")." -l '/Tools/Update' -x");
  }
}
exit(0);
?>
