#!/usr/bin/php -q
<?PHP
/* Copyright 2005-2022, Lime Technology
 * Copyright 2012-2022, Bergware International.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 2,
 * as published by the Free Software Foundation.
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 */
?>
<?
session_start();
$docroot = $docroot ?? $_SERVER['DOCUMENT_ROOT'] ?: '/usr/local/emhttp';

require_once "$docroot/webGui/include/Wrappers.php";
// Get the webGui configuration preferences
extract(parse_plugin_cfg('dynamix',true));

// add translations
$_SERVER['REQUEST_URI'] = 'plugins';
$_SESSION['locale'] = $display['locale'];
require_once "$docroot/webGui/include/Translations.php";

$console = !(isset($argv[1]) && $argv[1]=='nchan');

function write($message){
  global $console;
  if ($console) {
    echo $message;
  } else {
    $nchan = curl_init();
    curl_setopt_array($nchan,[
      CURLOPT_URL => 'http://localhost/pub/plugins?buffer_length=1',
      CURLOPT_UNIX_SOCKET_PATH => '/var/run/nginx.socket',
      CURLOPT_POST => 1,
      CURLOPT_POSTFIELDS => $message,
      CURLOPT_RETURNTRANSFER => true
    ]);
    curl_exec($nchan);
    curl_close($nchan);
  }
}

// check connectivity first
write(_("Checking connectivity")."...\n");
if (exec("wget --spider --no-check-certificate -nv -T10 -t1 https://www.msftncsi.com/ncsi.txt 2>&1|grep -o 'OK'")) {
  $check = popen('plugin checkall','r');
  while (!feof($check)) write(fgets($check));
  pclose($check);
} else {
  write(_("No response, aborting")."!\n");
}
?>