#!/usr/bin/php -q
<?PHP
/* Copyright 2005-2022, Lime Technology
 * Copyright 2012-2022, Bergware International.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 2,
 * as published by the Free Software Foundation.
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 */
?>
<?
$docroot = $docroot ?? $_SERVER['DOCUMENT_ROOT'] ?: '/usr/local/emhttp';

require_once "$docroot/webGui/include/Wrappers.php";
extract(parse_plugin_cfg('dynamix',true));

// add translations
$_SERVER['REQUEST_URI'] = 'plugins';
$login_locale = $display['locale'];
require_once "$docroot/webGui/include/Translations.php";

$file    = realpath($argv[1] ?? '');
$valid   = ['/var/tmp/','/tmp/plugins/'];
$good    = false;

function write($message){
  $nchan = curl_init();
  curl_setopt_array($nchan,[
    CURLOPT_URL => 'http://localhost/pub/changes?buffer_length=0',
    CURLOPT_UNIX_SOCKET_PATH => '/var/run/nginx.socket',
    CURLOPT_POST => 1,
    CURLOPT_POSTFIELDS => $message,
    CURLOPT_RETURNTRANSFER => true
  ]);
  curl_exec($nchan);
  curl_close($nchan);
}

usleep(300000);
if ($file) {
  foreach ($valid as $check) if (strncmp($file,$check,strlen($check))===0) $good = true;
  if ($good && pathinfo($file)['extension']=='txt') write(Markdown(file_get_contents($file)));
} else {
  write(Markdown("*"._('No release notes available')."!*"));
}
?>
